services:
  - type: web
    name: telegram-trading-assistant
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: TRADING_MODE
        value: LIVE
      - key: TELEGRAM_BOT_TOKEN
        value: 8937947792:AAGO58NK4N83vOBW4ONx5bKsbdA6p9_-5TU
      - key: AUTHORIZED_TELEGRAM_CHAT_IDS
        value: "1015884436"
      - key: TARGET_TELEGRAM_CHANNEL
        value: earnings_pulse
      - key: AUTO_EXECUTE_ORDER
        value: "true"
      - key: POLLING_INTERVAL_MS
        value: 5000
      - key: ANGEL_API_KEY
        value: FnjqYiUZ
      - key: ANGEL_CLIENT_CODE
        value: R704779
      - key: ANGEL_PIN
        value: "0812"
      - key: ANGEL_TOTP_SECRET
        value: HSLCI45Y7YK6MQVSODG3253DDY
      - key: ACCOUNT_CAPITAL
        value: 100000
      - key: RISK_PER_TRADE
        value: 0.01
      - key: ATR_MULTIPLIER
        value: 2
      - key: ATR_PERIOD
        value: 14
      - key: OCR_CONFIDENCE_THRESHOLD
        value: 60
